// <auto-generated />
using System;
using KnowledgePlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KnowledgePlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824150852_HardenTenantPolicyAgainstEmptySetting")]
    partial class HardenTenantPolicyAgainstEmptySetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kp")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnowledgePlatform.Domain.Cases.CanonicalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SourceCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("SourceResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SourceReference")
                        .IsUnique();

                    b.HasIndex("TenantId", "SourceResolvedAt");

                    b.ToTable("canonical_case", "kp");
                });

            modelBuilder.Entity("KnowledgePlatform.Domain.Evidence.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineReadability")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ObservedInCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ObservedInCaseId");

                    b.ToTable("evidence_item", "kp");
                });

            modelBuilder.Entity("KnowledgePlatform.Domain.Knowledge.Assertion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorLabel")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("KnowledgeRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ReplacedByAssertionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Verification")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeRecordId");

                    b.HasIndex("TenantId", "KnowledgeRecordId", "ReplacedByAssertionId");

                    b.ToTable("assertion", "kp");
                });

            modelBuilder.Entity("KnowledgePlatform.Domain.Knowledge.AssertionEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssertionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvidenceItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssertionId", "EvidenceItemId")
                        .IsUnique();

                    b.ToTable("assertion_evidence", "kp");
                });

            modelBuilder.Entity("KnowledgePlatform.Domain.Knowledge.KnowledgeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CauseName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("VisibilityScope")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Lifecycle");

                    b.ToTable("knowledge_record", "kp");
                });

            modelBuilder.Entity("KnowledgePlatform.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalKey")
                        .IsUnique();

                    b.ToTable("tenant", "kp");
                });

            modelBuilder.Entity("KnowledgePlatform.Domain.Knowledge.Assertion", b =>
                {
                    b.HasOne("KnowledgePlatform.Domain.Knowledge.KnowledgeRecord", null)
                        .WithMany("Assertions")
                        .HasForeignKey("KnowledgeRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgePlatform.Domain.Knowledge.AssertionEvidence", b =>
                {
                    b.HasOne("KnowledgePlatform.Domain.Knowledge.Assertion", null)
                        .WithMany("EvidenceLinks")
                        .HasForeignKey("AssertionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KnowledgePlatform.Domain.Knowledge.KnowledgeRecord", b =>
                {
                    b.OwnsOne("KnowledgePlatform.Domain.Knowledge.KnowledgeApproval", "LastApproval", b1 =>
                        {
                            b1.Property<Guid>("KnowledgeRecordId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("ApprovedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("approved_at");

                            b1.Property<string>("ApprovedByActor")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("approved_by_actor");

                            b1.Property<string>("Reason")
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("approval_reason");

                            b1.Property<string>("VisibilityScopeAfter")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("visibility_after");

                            b1.Property<string>("VisibilityScopeBefore")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("visibility_before");

                            b1.HasKey("KnowledgeRecordId");

                            b1.ToTable("knowledge_record", "kp");

                            b1.WithOwner()
                                .HasForeignKey("KnowledgeRecordId");
                        });

                    b.Navigation("LastApproval");
                });

            modelBuilder.Entity("KnowledgePlatform.Domain.Knowledge.Assertion", b =>
                {
                    b.Navigation("EvidenceLinks");
                });

            modelBuilder.Entity("KnowledgePlatform.Domain.Knowledge.KnowledgeRecord", b =>
                {
                    b.Navigation("Assertions");
                });
#pragma warning restore 612, 618
        }
    }
}
